## 验证抛出异常

1. 抛出异常来源方式

   - 来源于属性字段的判断

     ```java
     private Map<String, MessageHandler> messageHandlerMap = ...;
     public void handleMessage(Message message) {
         ...
         // 判断处理器映射非空
         if (CollectionUtils.isEmpty(messageHandlerMap)) {
             throw new ExampleException("消息处理器映射不能为空");
         }
         ...
     }
     ```

   - 来源于输入参数的判断

     ```java
     public void handleMessage(Message message) {
        ...
        // 判断获取处理器非空
        MessageHandler messageHandler = messageHandlerMap.get(message.getType());
        if (CollectionUtils.isEmpty(messageHandler)) {
           throw new ExampleException("获取消息处理器不能为空");
        }
        ...
     }
     ```

   - 来源于返回值的判断

     ```java
     public void handleMessage(Message message) {
        ...
        // 进行消息处理器处理
        boolean result = messageHandler.handleMessage(message);
        if (!reuslt) {
           throw new ExampleException("处理消息异常");
        }
        ...
     }
     ```

   - 来源于模拟方法的调用

     ```java
     public void handleMessage(Message message) {
        ...
        // 进行消息处理器处理
        boolean result = messageHandler.handleMessage(message); // 直接抛出异常
        ...
     }
     ```

   - 来源于静态方法的调用

     ```java
     // 可能会抛出IOException
     String response = HttpHelper.httpGet(url, parameterMap);
     ```

2. 抛出异常验证方式: 4

   ![avatar](/static/image/test/junit-verify-exception.png)

   - 通过 try-catch 语句验证抛出异常

     ```java
     @Test
     public void testCreateUserWithException() {
        // 模拟依赖方法
        Mockito.doReturn(true).when(userDAO).existName(Mockito.anyString());

        // 调用测试方法
        UserCreateVO userCreate = new UserCreateVO();
        try {
           userCreate.setName("changyi");
           userCreate.setDescription("Java Programmer");
           userService.createUser(userCreate);
        } catch (ExampleException e) {
           Assert.assertEquals("异常编码不一致", ErrorCode.OBJECT_EXIST, e.getCode());
           Assert.assertEquals("异常消息不一致", "用户已存在", e.getMessage());
        }

        // 验证依赖方法
        Mockito.verify(userDAO).existName(userCreate.getName());
     }
     ```

   - _通过@Test 注解验证抛出异常: expected_

     ```java
     @Test(expected = ExampleException.class)
     public void testCreateUserWithException() {
        // 模拟依赖方法
        Mockito.doReturn(true).when(userDAO).existName(Mockito.anyString());

        // 调用测试方法
        UserCreateVO userCreate = new UserCreateVO();
        userCreate.setName("changyi");
        userCreate.setDescription("Java Programmer");
        userService.createUser(userCreate); // 此处后续不能执行

        // 验证依赖方法(不会执行)
        Mockito.verify(userDAO).existName(userCreate.getName());
     }
     ```

   - _通过@Rule 注解验证抛出异常: 验证异常原因和消息_ + 建议使用 Assert.assertThrows

     ```java
     @Rule public ExpectedException exception = ExpectedException.none();

     @Test
     public void testCreateUserWithException1() {
        // 模拟依赖方法
        Mockito.doReturn(true).when(userDAO).existName(Mockito.anyString());

        // 调用测试方法
        UserCreateVO userCreate = new UserCreateVO();
        userCreate.setName("changyi");
        userCreate.setDescription("Java Programmer");
        exception.expect(ExampleException.class);
        exception.expectMessage("用户已存在");
        userService.createUser(userCreate); // 此处后续不能执行

        // 验证依赖方法(不会执行)
        Mockito.verify(userDAO).existName(userCreate.getName());
     }
     ```

   - **通过 Assert.assertThrows 方法验证抛出异常**

     ```java
     @Test
     public void testCreateUserWithException() {
        // 模拟依赖方法
        Mockito.doReturn(true).when(userDAO).existName(Mockito.anyString());

        // 调用测试方法
        UserCreateVO userCreate = new UserCreateVO();
        userCreate.setName("changyi");
        userCreate.setDescription("Java Programmer");
        ExampleException exception = Assert.assertThrows("异常类型不一致", ExampleException.class, () -> userService.createUser(userCreate));
        Assert.assertEquals("异常编码不一致", ErrorCode.OBJECT_EXIST, exception.getCode());
        Assert.assertEquals("异常消息不一致", "用户已存在", exception.getMessage());

        // 验证依赖方法
        Mockito.verify(userDAO).existName(userCreate.getName());
     }
     ```

3. 验证抛出异常问题

   - 未验证抛出异常类型
   - 未验证抛出异常属性
   - 未验证抛出异常部分属性
   - 未验证抛出异常原因
   - 未验证相关方法调用
   - best practice: 对异常类型、异常属性、异常原因等进行验证外, 还需对抛出异常前的依赖方法调用进行验证

     ```java
     // 模拟依赖方法
     Throwable e = new RuntimeException();
     Mockito.doThrow(e).when(userDAO).create(Mockito.any(UserCreateVO.class));

     // 调用测试方法
     String text = ResourceHelper.getResourceAsString(getClass(), path + "userCreateVO.json");
     UserCreateVO userCreateVO = JSON.parseObject(text, UserCreateVO.class);
     ExampleException exception = Assert.assertThrows("异常类型不一致", ExampleException.class, () -> userService.createUser(userCreateVO));
     Assert.assertEquals("异常编码不一致", ErrorCode.OBJECT_EXIST, exception.getCode());
     Assert.assertEquals("异常消息不一致", “创建用户异常”, exception.getMessage());
     Assert.assertEquals("异常原因不一致", e, exception.getCause());

     // 验证依赖方法
     ArgumentCaptor<UserDO> userCreateCaptor = ArgumentCaptor.forClass(UserDO.class);
     Mockito.verify(userDAO).create(userCreateCaptor.capture());
     text = ResourceHelper.getResourceAsString(getClass(), path + "userCreateDO.json");
     Assert.assertEquals("用户创建不一致", text, JSON.toJSONString(userCreateCaptor.getValue()));
     ```

4. 验证抛出异常准则

   - 必须验证所有抛出异常
   - 必须验证异常类型、异常属性、异常原因
   - 验证抛出异常后, 必须验证相关方法调用
